### ISSUE TITLE
Virtual Browse covering actions links

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/discovere-restyle#10]
The Virtual Browser option is covering the Actions dropdown.  See here:  http://discovere.emory.edu/discovere:default_scope:01EMORY_ALMA21203370600002486
Click on virtual browse and then try to use the actions menu.

**Comment by kristianserrano** [comment]
I'm seriously considering hiding the actions menu in virtual browse. Does anyone have a convincing argument against this idea?

**Comment by kristianserrano** [comment]
The real fix would be  adding !important to the z-index for the selector `body.EXLFullView div.EXLTabHeaderButtons ol.EXLTabHeaderButtonSendToList`

**Comment by eipeele** [comment]
@kristianserrano is there an ETA for when this bug will be fixed?

**Comment by kristianserrano** [comment]
@eipeele Sometime today.
