### ISSUE TITLE
Link logo to start page

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/discovere-restyle#12]
Currently the logo is not linked at all.

**Comment by laura-ake** [comment]
I assume you mean the logo that says Emory Libraries and Information Technology | DiscoverE?

Ideally, the DiscoverE part would link to DiscoverE (start page) but the other part  -shouldn't it go out somewhere?  libraries.emory.edu not it.emory.edu :-) .   

If the user started on, say, http://web.library.emory.edu/  (or one of the other library pages) using a search box, it'd be nice to give them a chance to get back to where they came in from.

**Comment by kristianserrano** [comment]
No, the split linked logo has proven to be a bad anti-pattern in testing. The logo should only link to the homepage of the current site. Users can't see the split links and often get confused and frustrated when they land on a site other than the current site.

**Comment by kristianserrano** [comment]
Fixed by #43
