### ISSUE TITLE
Kiosk view

### ISSUE THREAD

**Issue by laura-ake** [emory-libraries/discovere-restyle#14]
Do we need to do a "restyled" version of kiosk view right away?  I'm not sure we had any of the issues with it that we had with discovere view.  Kiosk is so scaled back.  I'm thinking it would need to keep its own html, header and footer and image file, and maybe the .css we use for discovere would work, or maybe it would need tweaking.  Unless there are complaints now, I will take a quick look and plan to deal with it later (next week)

**Comment by kristianserrano** [comment]
Functionally, probably not. We're not too concerned with reponsive layout in kiosk for example.

Branding and visual consistency would be nice though.

**Comment by laura-ake** [comment]
I will leave this to you to decide if it needs to be an active issue.

Is there a way to park issues here in GitHub?

**Comment by kristianserrano** [comment]
I'm not sure it's up to me. I think this is a question for Core Systems to answer.

Regarding parking issues, just leave them open. We could create a column in waffle.io.

**Comment by AGCooper** [comment]
I would leave the Kiosk be until we go to the New UI. It's very minimalist as it is and only for quick look ups. I would close this issue and reconsider it for the New UI project.

**Comment by eipeele** [comment]
or for whatever new system/new UI is decided upon.

I wouldn't change anything in Kiosk right now mainly because there are small things that change that end up showing/hiding links that shouldn't.

**Comment by kristianserrano** [comment]
Based on the conversation above, do we want to close this and mark it as "wontfix?"

**Comment by eipeele** [comment]
yes
