### ISSUE TITLE
After choosing Permalink in Actions menu, focus in wrong place

### ISSUE THREAD

**Issue by laura-ake** [emory-libraries/discovere-restyle#16]
After clicking Permalink in Actions menu, the focus shifts to the bottom of the page.  Should go to the top of the Full record where the permalink is displayed.

**Comment by kristianserrano** [comment]
Primo seems to have some JS that jumps the page. I can change the CSS on `#exliPrimoLightBoxdiv` from `position: absolute` to `postion: fixed`.

The page will still jump, but at least the lightbox will still be in view.

**Comment by kristianserrano** [comment]
Fixed in #21
