### ISSUE TITLE
Logo not always showing properly on services page

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/discovere-restyle#24]
The Emory banner's logo doesn't always show properly for the services page.  Sometimes, the SVG logo will overwhelm the page, and the blue background will not appear.  A page with the problem looks like [this](https://emory.box.com/s/jrh9jdqv62m48eybd1y4zkq47si87haa).  This doesn't happen all of the time, and will work in one browser but not another at the same time.  I copied the page source just in case you couldn't replicate the issue.  The page source when it views [correctly](https://emory.box.com/s/vk0sdf7iqx2h6z4z6nuap1xu90t2a59k), and when it [doesn't](https://emory.box.com/s/n50efscutwg6w1ghlrduhgwxwz851ven).

To try and replicate:
1)  go to HSL's website
2)  choose pubmed
3) search something in pubmed
4)  click on Find It @ Emory
5)  This takes you to the services page, which is the problem.

This problem has so far happened in Chrome and Firefox.  It happened on my 11" Air and Bonnie at HSL at the same problem with her Desktop.

Let me know if you need more info.

**Comment by kristianserrano** [comment]
I can't see any of the files at your Box links. Can you check the permissions? Also, what is HSL?

**Comment by eipeele** [comment]
You should have access now.  HSL = Health Sciences Library

**Comment by kristianserrano** [comment]
Interesting. I've always referred to them as WHSC (which is how they refer to themselves).

Checking the screenshots now.

**Comment by kristianserrano** [comment]
Think it’s fixed. Please test if/when you get a chance. No code to commit. This was all Primo BO settings.

**Comment by kristianserrano** [comment]
Has anyone confirmed that everything is OK now?

**Comment by eipeele** [comment]
I confirmed on Slack, but not on GitHub. I checked yesterday, and it looks great.

**Comment by kristianserrano** [comment]
Thanks for confirming.
