### ISSUE TITLE
Citation linker won't scroll so user can click submit

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/discovere-restyle#30]
For the book and article sections of the citation linker, the lightbox extends beyond the frame of a small screen (I'm on an 11" Mac), and will not allow scrolling.  Patron can't get to the fields below the fold or see the submit button.  You can recreate this by going to [discovere.emory.edu](discovere.emory.edu) and clicking on citation linker and then choosing book or article.  Larger screens are likely not an issue.  Example:  
![citation_linker](https://user-images.githubusercontent.com/5278377/36791894-f8d58c88-1c66-11e8-95ad-5284b07e15e4.png)

**Comment by kristianserrano** [comment]
Did we want this fixed for this upcoming release?

**Comment by eipeele** [comment]
not unless it's a simple fix that can easily be tested by tomorrow.  otherwise, it can go next time.
