### ISSUE TITLE
Archives icon - restore to search results

### ISSUE THREAD

**Issue by laura-ake** [emory-libraries/discovere-restyle#35]
We have a special icon for records with type "archives" (descriptions of archival collections) in Discovere, appearing to the left of the brief item fields in search results.  It stopped showing up at some point and was noticed after we applied the re-style.  Here's info from the email I sent Kristian:

What we did before:  
This is the statement we added:  

/*  classic thumbnails added by cspald3 20131012 */
.EXLResultMediaTYPEarchives .multipleCoverImageContainer {
    background-image: url(../images/discoverE/icon_archive.png);
}

That's giving the relative path (from the top level images directory in fe_web) to where the icon_archive.png file.  This is not inside the uploaded_files directory.

We don't have to put it there, we could move it to the directory we can send it to using upload utility in back office if you prefer.  But apparently it's been safe from overwriting there, so far.  We could also point to it externally but that seems unnecessary since the file won't be changing.

Let me know if you have questions -- and not huge priority, just would be nice to take care of this.

**Comment by laura-ake** [comment]
Associate this issue with branch AddImageIcon (can't see how after the fact but close this when that one is merged).

**Comment by kristianserrano** [comment]
You associate it with the pull request by citing this issue in the PR itself.
