### ISSUE TITLE
Business format drop for search wrong position

### ISSUE THREAD

**Issue by eipeele** [emory-libraries/discovere-restyle#36]
When going to http://discovere.emory.edu/primo_library/libweb/action/search.do?vid=business, the drop menu to the left of the search bar appears in a weird place where the user can't really see what the options are or realize they can use it.  See image for details.
![business_view](https://user-images.githubusercontent.com/5278377/40673405-b4ccc3ce-633f-11e8-8035-129db7c13c84.png)

**Comment by eipeele** [comment]
Do you know what the differences are between the CSS tables?

**Comment by kristianserrano** [comment]
I think we can. Perhaps just change the CSS URLs in the tables and see what breaks for the business view?

I can work on making an SVG logo and header and footer static HTML files by end of day Thursday.

**Comment by laura-ake** [comment]
Hi Kristian and Elizabeth, I checked in with Rosy on this.  This summer is not the time to bring up changing (or doing away with) Business View.  So if making the special SVG header and static HTML for GBL is not inordinately time consuming, go ahead with that.  I'm not aware of anything else in their view that should be different from the "discovere" view so the "restyled" css and js SHOULD work (or we will find out in Sandbox).   I'll want to tip them off that we're re-styling their view once we get it in SB so they aren't caught off guard by anything.

**Comment by kristianserrano** [comment]
Did you talk about keeping the business view but not the logo?

**Comment by kristianserrano** [comment]
Waiting for EPS copy of the GBL logo from Marketing and Communications. Emailed Gretchen for a copy.

**Comment by eipeele** [comment]
@kristianserrano I have updated the css mapping table for business from Primo_default.3.0.css;../uploaded_files/business/css/eulHeader.css;;../uploaded_files/discovere/css/eulHomeContent.css;../uploaded_files/discovere/css/EULDefaultOverrides.css 
to
Primo_default.3.0.css;https://template.library.emory.edu/systems/ex-libris/primo/discovere/sandbox/css/discovere.css
and have deployed everything.
